services:
  # the actual db
  login-mongo:
    image: mongo
    restart: always
    volumes:
      - ./import:/docker-entrypoint-initdb.d:ro
    networks:
      - login-internal-net

  # the management interface to the db 
  login-mongo-express:
    depends_on:
      - login-mongo
    image: mongo-express
    restart: always
    ports:
      # for debug purposes only
      - ${LOGIN_DB_UI_PORT:-8081}:8081
    networks:
      - login-internal-net
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://login-mongo:27017/
      - ME_CONFIG_MONGODB_SERVER=login-mongo
      # TODO: use auth to access this or remove entirely on deploy
      - ME_CONFIG_BASICAUTH=false

  # the api built on top of the db
  login-api:
    build: .
    depends_on:
      - login-mongo
    ports:
      - ${LOGIN_API_PORT}:3000
    networks:
      - login-internal-net
      - town-of-saviom-shared-net
    environment:
      # mongodb-container -> nome container del db
      # login -> nome del db
      - MONGO_URI=mongodb://login-mongo:27017/login
      # production or debug
      - NODE_ENV=${NODE_ENV}
      # origin url accepted by cors
      - CORS_ORIGIN=${CORS_ORIGIN}

networks:
  login-internal-net:
    driver: bridge
  town-of-saviom-shared-net:
    external: true