services:
  # the actual db
  mongo:
    image: mongo
    container_name: login-mongodb-container
    restart: always
    volumes:
      - ./import:/docker-entrypoint-initdb.d:ro
    networks:
      - login-internal-net

  # the api built on top of the db
  frontend:
    build: .
    container_name: login-api
    depends_on:
      - mongo
    ports:
      - ${PORT}:${PORT}
    networks:
      - login-internal-net
      - town-of-saviom-shared-net
    environment:
      # mongodb-container -> nome container del db
      # login -> nome del db
      - MONGO_URI=mongodb://login-mongodb-container:27017/login
      # production or development
      - NODE_ENV=production
      - PORT=${PORT}

networks:
  login-internal-net:
    driver: bridge
  town-of-saviom-shared-net:
    external: true